version: "3.9"
services:
  spring-websocket-template:
    build: .
    container_name: spring-websocket-template
    ports:
      - "80:80"
    env_file: .docker.env
    networks:
      - kafka_network
      - jaeger_network
      - rabbitmq_network
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost/actuator/health || exit 1" ]
    deploy:
      resources:
        reservations:
          memory: 512M
          cpus: "0.25"
        limits:
          memory: 512M
          cpus: "0.25"

networks:
  kafka_network:
    name: kafka_network
    external: true
  jaeger_network:
    name: jaeger_network
    external: true
  rabbitmq_network:
    name: rabbitmq_network
    external: true
