spring:
  kafka:
    jaas:
      enabled: false
    properties:
      sasl:
        mechanism: PLAIN
    security:
      protocol: PLAINTEXT

management:
  tracing:
    sampling:
      probability: 1.0
