apiVersion: v1
kind: Secret
metadata:
  name: spring-websocket-template-secret
  namespace: template
type: Opaque
data:
  SPRING_KAFKA_JAAS_OPTIONS_USERNAME:
  SPRING_KAFKA_JAAS_OPTIONS_PASSWORD:
  SPRING_WEBSOCKET_RELAY_LOGIN:
  SPRING_WEBSOCKET_RELAY_PASSCODE:
