apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-websocket-template
  namespace: template
  labels:
    app: spring-websocket-template
spec:
  selector:
    matchLabels:
      app: spring-websocket-template
  template:
    metadata:
      labels:
        app: spring-websocket-template
    spec:
      containers:
        - name: spring-websocket-template
          image: jleijendekker/spring-websocket-template:1.0.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: spring-websocket-template-config
            - secretRef:
                name: spring-websocket-template-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 20
            timeoutSeconds: 15
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 15
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: 1G
              cpu: 0.5
            limits:
              memory: 1G
              cpu: 0.5

---
apiVersion: v1
kind: Service
metadata:
  name: spring-websocket-template-service
  namespace: template
spec:
  selector:
    app: spring-websocket-template
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
