on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: "temurin"
          cache: "gradle"
      - name: Execute Gradle Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test -i
        env:
          SPRING_PROFILES_ACTIVE: ci
