on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: ${{ inputs.environment }}
    steps:
      - name: Setup java 20
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: "temurin"
      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Execute gradle test
        run: ./gradlew test -i
        env:
          SPRING_PROFILES_ACTIVE: ci
